# Generated by Django 5.2.11 on 2026-02-05 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200, unique=True)),
                ('ingredients', models.TextField(help_text='Enter ingredients, one per line or comma-separated')),
                ('preparation_steps', models.TextField(help_text='Enter preparation steps')),
                ('cooking_time', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('servings', models.IntegerField(default=4, help_text='Number of servings')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('appetizer', 'Appetizer')], default='dinner', max_length=50)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
