# Generated by Django 5.2.15 on 2026-06-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Optional YouTube video link for this recipe (not required)', max_length=500, null=True),
        ),
    ]
